### PR TITLE
Add CustomEvent polyfill

### PR DESCRIPTION
**Pull request by rianby64**
Refers to #64 issue.
The motivation behind this polyfill is that I don't want to use two polyfills. One for all those that I need, and a second one with a sole CustomEvent.
Hope this addition will be useful.

### CODE REVIEW

**Comment by inexorabletash** [comment]
Apologies for the delay in reviewing this. I'll try and get to it soon.

**Comment by inexorabletash** [comment]
Oh, and adding a test would help speed up the process if you have time for that. If not I'll take care of it.

**Comment by rianby64** [comment]
Also I've my doubts about where to put the code? dom.js or web.js ? Can you give me a hint, tip? I was looking for a task at package.json that compiles all the files into a main file, but couldn't find it.

I appreciate any help you can provide, @inexorabletash

**Comment by inexorabletash** [comment]
Thanks - I'll try and test/review/merge tonight.

> I've my doubts about where to put the code? dom.js or web.js ? Can you give me a hint, tip? I was looking for a task at package.json that compiles all the files into a main file, but couldn't find it.

dom.js is the right place, since it's from [DOM Standard](https://dom.spec.whatwg.org/). I just use a pre-commit hook to concatenate files to create web.js and polyfill.js and create minified copies, so I'll take care of that.

**Comment by inexorabletash** [comment]
Thanks!

**Pull request merged**
