### PR TITLE
Add global fallbacks

### PR DESCRIPTION
**Pull request by sendyhalim**
So I'm using polyfill with webpack but it doesn't polyfill anything, after a few debugging I found that `webpack` wraps the global window, so `this` context is not the global window. 

```
this === window // false
```

I copied the code from here, and it works.

https://github.com/bjornstar/blob-polyfill/blob/master/Blob.js#L211

### CODE REVIEW

**Comment by inexorabletash** [comment]
That seems particularly convoluted, referencing many nonstandard properties.

Does using `self` consistently (which is an alias for the global in web contexts) fix the problem webpack introduces? I'd be happier to change `this` to `self` consistently as that is entirely standard.

**Comment by sendyhalim** [comment]
How about using window as the first option then fallback to `this`? Below code works with `webpack`

```
(typeof window !== 'undefined' && window || this)
```

**Comment by inexorabletash** [comment]
`self` is preferable, as it is consistent between both `Window` and `Worker` contexts. Can you try `self` and report back?

**Comment by sendyhalim** [comment]
@inexorabletash sure I'll test it

**Comment by sendyhalim** [comment]
@inexorabletash yep using `self` works, I'll push another commit

**Comment by inexorabletash** [comment]
Thanks!

**Comment by sendyhalim** [comment]
You're welcome :smile:

**Pull request merged**
